print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? €"))
tip = float(input("How much % tip would you like to give ? 5,10,12 or 15? "))
number_of_people = int(input("How many people would like to split the bill? "))
split_per_person = round((total_bill + (total_bill * tip / 100.0)) / number_of_people, 2)
print(f"Each person should pay: {split_per_person} €")
